server.port = 8090

spring.application.name=promts_test_server
# Profiles priority model, mock, neuro, dbmock
spring.profiles.default=dbmock

# DB SETTINGS
# Connecting to data source on YDV
#spring.datasource.url=...
#spring.datasource.username=...
#spring.datasource.password=...

# Local machine
#spring.datasource.url=jdbc:postgresql://localhost:5432/promts_db
#spring.datasource.username=app_database_user
#spring.datasource.password=36842989

# Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/promts_db
spring.datasource.username=app_database_user
spring.datasource.password=36842989

# Liquibase settings
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:database/changelog/db.changelog--master.yaml

# Disabling the HibernateDDL for using Liquibase
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true